### ISSUE TITLE
Complete files for sudo dpkg -i 

### ISSUE THREAD

**Issue by iandol** [rsteube/carapace-bin#1602]
### Request

When I try to install a DEB package using sudo carapace fails to complete the files:

```
error: no candidates

▶︎ sudo dpkg -i [tab]
```

Without sudo it works (and with sudo without carapace it works), if I try to use `--` to stop completion it still fails.

### Proposed solution

Allow to complete files and folders, `sudo dpkg -i` is a fairly common invocation.

### Anything else?

Thanks as always for a great tool!!!

**Comment by rsteube** [comment]
Oh, that is indeed quite an issue (and one i've lost sight of to be honest).
The reason for this is that carapace has its own completer for `sudo` which has support for embedding other completers.
To my knowledge shells don't have decent support for this apart from `sudo` where i believe some special _hack_ is done.

The reason that `dpkg` is not working with `sudo` and `carapace` being enabled is that there is no `dpkg` completer known to `carapace` and a fallback to the shell's completion is missing.
A fallback to file completion is possible, but the shell might be able to do quite a bit more (like completing flags).

Most shells don't provide a good way to invoke completers registered in them so this isn't exactly easy.
`Fish` is pretty uncomplicated though and since there is a bridge for it in carapace that might be quick workaround for now.
So if there is no completion provided try to fall back to what fish provides (if installed).

**Comment by iandol** [comment]
Hi @rsteube — thanks so much for the initial workaround and later fixes. I don't have Fish installed, only zsh/bash and my daily driver elvish. So #1603 should allow a fallback without any other tweaks that need to be made? I'm happy to test when the merge makes it into a release.

Thanks as always!!!

**Comment by iandol** [comment]
Can confirm this is fixed with V0.24.1, thank you!!!
