### ISSUE TITLE
git blame: can't autocomplete file path in nushell

### ISSUE THREAD

**Issue by WindSoilder** [rsteube/carapace-bin#1617]
### Current Behavior

As title, I have a file called `a.txt`, then I type `git blame a<tab>`, it shows that "NO RECORDS FOUND"

### Expected Behavior

I would expect it shows `a.txt`.

### Version

0.18.0

### OS

- [ ] Linux
- [X] OSX
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [X] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

### Anything else?

I think it generates auto-complete options for commit hash rather than file path...
![img](https://user-images.githubusercontent.com/22256154/229004206-d47a09e6-c4aa-4620-ad9c-bcfb7463d708.png)

**Comment by rsteube** [comment]
Should work when you try completing it with a file path prefix like `git blame ./` (also `/` and `~`).
Git blame can be used as `git blame <file>`  but also as `git blame <ref> <file>`.
For cases like this i often leave file completion out in the default and only show them when the prefix is set for better clarity in the results (gets quite large otherwise and mixed up).

**Comment by rsteube** [comment]
https://github.com/rsteube/carapace-bin/discussions/1655
