### ISSUE TITLE
Question about relation to other completion frameworks

### ISSUE THREAD

**Issue by SuperSandro2000** [rsteube/carapace-bin#938]
I am bit confused how the relation of carapace-bin is to other completion frameworks like bash-completion, fzf or bleh.sh. Is it supposed to be an addition to them or does it replace them complete? So far I saw no compatibility issues with bash-completion or fzf since it overwrites their handling but [ble.sh](https://github.com/akinomyoga/ble.sh/) breaks at least chmod and the result is ``chmod '0 (none)' carapace-bin_0.9.1_Linux_x86_64.tar.gz``.

**Comment by SuperSandro2000** [comment]
> AFAIK this is just a fuzzy finder or not? 

It also adds some completion to for example ssh or dig.

> does it provide sth. like menu completion?

yeah, it does.

**Comment by rsteube** [comment]
> > does it provide sth. like menu completion?
> 
> yeah, it does.

It would need a different output then. Leaving out the descriptions is certainly possible, just not very userful then.
Seems `bleh.sh` does have some support for descriptions: https://github.com/akinomyoga/ble.sh/issues/155 , but from what I am reading it is generated internally from help/man pages.

**Comment by akinomyoga** [comment]
It's just undocumented, but it is possible to generate descriptions with candidates for `ble.sh`. I'm not sure if you are interested in supporting it, but here is an example:

```bash
_comp_cmd_test1() {
  if [[ ${BLE_ATTACHED-} ]]; then
    # If ble.sh is in the attached state.

    # Change the menu style to "desc" for the current completion
    bleopt complete_menu_style=desc

    # Generate filename or directory name (The description is automatically
    # generated from the filename for "file").
    ble/complete/cand/yield file 'file.txt'

    # Generate words with description.
    ble/complete/cand/yield word 'my-word' 'This is a description for my-word.'

    # Generate option with OPTARG indicated in the list.  In the third argument
    # $'OPTION\x1cOPTARG\x1cSUFFIX\x1cDESCROPTION', FS ($'\x1c') is used to
    # separate OPTION, OPTARG indicator, SUFFIX that is inserted after inserted
    # the unique completion, and DESCRIPTION
    ble/complete/cand/yield mandb '--option' $'--option\x1c=<something>\x1c=\x1cThis is a description for the option'

  else
    # If ble.sh is not loaded or is in the detached state, just generate
    # candidates for the default progcomp system of Bash.

    COMPREPLY+=(file.txt)
    COMPREPLY+=(candidate)
    COMPREPLY+=(--option)

  fi
}
complete -F _comp_cmd_test1 test1
```

![image](https://user-images.githubusercontent.com/8982192/154840553-98607ad6-15df-4b53-bf75-cf78fd10389d.png)

Some additional adjustments might be needed for the detailed behavior.
- For example, the word specified to the second argument of `ble/complete/cand/yield` should not be quoted. It will be automatically quoted by `ble.sh` when the candidate contains special characters.
- For another example, the directory suffix `/` is only inserted for the directory names generated as `file`, etc. If you want to show a description for directory names, you need to define a new completion "action" (that is specified to the first argument of `ble/complete/cand/yield`). To define a new action, maybe you can reference the existing implementation for [`action:mandb`](https://github.com/akinomyoga/ble.sh/blob/f62fc04f42dc5fcac9e3063a1bc5e0c3351d5920/lib/core-complete.sh#L3693-L3718) or [`action:file`](https://github.com/akinomyoga/ble.sh/blob/master/lib/core-complete.sh#L1619-L1648). But, actually these internal APIs might be changed in the future, so please let me know if you want to maintain it. I'll add it to my list of external dependencies on ble.sh and will submit PR when there will be breaking changes.

**Comment by rsteube** [comment]
Added experimental support. There are likely some issues, but basics seem to work alright.

- optarg not yet working
- seems like there is some automatic invocation of completion (`complete_auto_complete`)? which is bad for slow completions
- `BLE_ATTACHED` is not exported so `bash-ble` must be passed explicitly (no automatic detection yet)

```sh
bleopt complete_auto_complete=
source <(carapace _carapace bash-ble)
```

[![asciicast](https://asciinema.org/a/470338.svg)](https://asciinema.org/a/470338)

**Comment by SuperSandro2000** [comment]
Great! I am going to test that for some completions in the next days.

So far I always detected ble.sh with the `BLE_VERSION` env which is exported I think.

**Comment by akinomyoga** [comment]
> * seems like there is some automatic invocation of completion (`complete_auto_complete`)?

Yes. You can detect whether the current completions are automatically invoked one or not by the following test:

```bash
[[ :$comp_type: == *:auto:* ]]
```

If the completion function returns without generating any candidates, the default completion by `ble.sh` will be used.

> * which is bad for slow completions

If the bottleneck is the `for` loop at the ble.sh side, there is a mechanism to detect the user input and cancel the completion. You can insert the following line:

```diff
   for cand in "${c[@]}"; do
+    ((cand_iloop++%bleopt_complete_polling_cycle==0)) && ble/complete/check-cancel && return 148
     [ ! -z "$cand" ] && ble/complete/cand/yield mandb "${cand%%$'\t'*}" "${cand##*$'\t'}"
   done
```

> * `BLE_ATTACHED` is not exported so `bash-ble` must be passed explicitly (no automatic detection yet)

There is no plan of exporting `BLE_ATTACHED` because it indicates that ble.sh is in the attached state in *the current Bash process*. If we export it, then the child Bash shells started from a ble.sh session also inherit the variable regardless of whether ble.sh is loaded in the child shells.

> So far I always detected ble.sh with the `BLE_VERSION` env which is exported I think.

`BLE_VERSION` is not exported for the same reason.

Anyway, if the determination of the completion type would be determined at the initialization stage, we should use `BLE_VERSION` rather than `BLE_ATTACHED`, because ble.sh is not yet attached in the initialization stage. Another problem of referencing some variables might be the sourcing order of `ble.sh` and `"$(caraspace _caraspace)"`. If `caraspace` is initialized before `ble.sh` is sourced, `caraspace` cannot automatically detect `ble.sh`. So, I think the current `source <(carapace _carapace bash-ble)` is more reasonable than automatic detection.

It should be noted that, if the type of completion is statically determined at the initialization time, the completion will not work when ble.sh is in the detached state (though `ble-detach` is currently an undocumented feature). But I think it's rare to use Bash in the detached state when ble.sh is loaded, so we don't have to care about it too much.

So far I couldn't take time to see how to use `caraspace`, but later I will try to test them. Thank you.

**Comment by rsteube** [comment]
Ah, i expected `ble.sh` to be continously activated - needs the fallback then.
Regarding the automatic completions my main problem was that I couldn't cancel them.
There are a couple of slow completions (due to the background service being queried) where this can cause some issues - might be best to skip these in the script with the check for now.
Automatic detection is just a convenience function anyway.

**Comment by akinomyoga** [comment]
> Regarding the automatic completions my main problem was that I couldn't cancel them. There are a couple of slow completions (due to the background service being queried) where this can cause some issues - might be best to skip these in the script with the check for now.

Ah, OK, if so. maybe you can call the command using `ble/util/conditional-sync`. For example, for `chmod`, the invocation of `carapace chmod bash-ble` may be replaced by the following one:

```bash
ble/util/conditional-sync 'carapace chmod bash-ble' '! ble/complete/check-cancel' 128 progressive-weight
```

`ble/util/conditional-sync` kills the command (specified to the first argument) when the condition (specified to the second argument) becomes unsatisfied. The third argument specifies the interval of checking the condition (128 milliseconds in this case). The fourth argument is a colon-separated list of options to control the detailed behavior. The accepted options are `progressive-weight` and `timeout=TIMEOUT` where `TIMEOUT` is an integer in millisecond unit.
